---
- hosts: web
  user: ansible
  become: true
  tasks:         
   - name: install apache at latest      
     yum:
       name: httpd
       state: latest

   - name: start apache 
     service:
         name: httpd
         state: started
         enabled: yes
              

   - name: create index.html file
     file:
       path: /var/www/html/index.html
       state: touch
    
   - name: edit index.html file
     lineinfile: 
      path: /var/www/html/index.html
      line: "this is my first website"




