#!/bin/bash
# Run this as a script
# create an ubuntu-18.04 ec2 instance in aws
sudo hostname docker
sudo apt update -y
sudo apt install docker.io -y
sudo usermod -aG docker ariella  ( replace ariella by ubuntu if using aws ) 

# Install java as jenkins dependency
sudo apt install openjdk-11-jdk -y
# install jenkis in ubuntu:
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
    /usr/share/keyrings/jenkins-keyring.asc > /dev/null

echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null

sudo apt-get update
sudo apt-get install jenkins -y
sudo systemctl start jenkins
sudo sudo ufw allow 8080
sudo ufw allow OpenSSH
sudo ufw enable
sudo ufw status
sudo useradd jenkins 
sudo usermod -aG docker jenkins 
echo "jenkins  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/jenkins 
docker --version
#sudo su - jenkins
============================================================================================================================================================================
TO SETUP STATIC IP ON UNBUNTU SERVER
# cd /etc/netplan
# vim 01-network-manager-all.yaml
    # Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ens160:
      dhcp4: no
      addresses: [192.168.0.240/24]
      gateway4: 192.168.0.1
      nameservers:
       addresses: [192.168.0.32] this the ip of my dns server. if you don't have a dns server put the primary and secondary ip of your local dns separated by colon
# sudo netplan try and press "enter" if there is no error or just run " sudo netplan apply" to save the changes
=========================================================================================================================================================================
